dataloader:
  train:
    batch_size: 1024
    shuffle: True
  val:
    batch_size: 1024
    shuffle: False
  test:
    batch_size: 1024
    shuffle: False

trainer:
  gpus: 1
  max_epochs: 2
  #log_every_n_steps: 10

loss:
  train:
    weight: 1
    name: CrossEntropy
  val:
    weight: 1
    name: CrossEntropy

model:
  Classification:
    conv2d: ok

logger:
  train:
    accuracy: True
    hp_metric: accuracy
  val:
    accuracy: True

optimizers:
  - Adam

lr_scheduler:
  - None

callbacks:
  - None
