model:
    encoder:
        level1:
            in_channels: 3
            out_channels: 64
            residual: True
            batch_norm: True
        level2:
            in_channels: 64
            out_channels: 128
            residual: True
            batch_norm: True
        level3:
            in_channels: 128
            out_channels: 256
            residual: True
            batch_norm: True
        level4:
            in_channels: 256
            out_channels: 512
            residual: True
            batch_norm: True
        level5:
            in_channels: 512
            out_channels: 1024
            residual: True
            batch_norm: True
    decoder:
        level4:
            in_channels: 1024
            out_channels: 512
            residual: True
            batch_norm: True
        level3:
            in_channels: 512
            out_channels: 256
            residual: True
            batch_norm: True
        level2:
            in_channels: 256
            out_channels: 128
            residual: True
            batch_norm: True
        level1:
            in_channels: 128
            out_channels: 64
            residual: True
            batch_norm: True
    head:
        in_channels: 64
        out_channels: 1

data:
    train_folder: 'data/train'
    valid_folder: 'data/valid'
    test_folder: 'data/test'

    processing:
        ignore_index: &ignore_index -1
        mode: &mode 'binary'

dataset:
    train:
        FolderDataSet:
            image_transforms:
                ToTensor:
                CenterCrop: 128
            target_transforms:
                ToTensor:
                CenterCrop: 128
    valid:
        FolderDataSet:
            image_transforms:
                ToTensor:
                CenterCrop: 128
            target_transforms:
                ToTensor:
                CenterCrop: 128
    test:
        FolderDataSet:
            image_transforms:
                ToTensor:
                CenterCrop: 128
            target_transforms:
                ToTensor:
                CenterCrop: 128

dataloader:
    train:
        batch_size: 2
        num_workers: 2
    valid:
        batch_size: 2
        num_workers: 2
    test:
        batch_size: 2
        num_workers: 2

run:
    train: True
    valid: True
    test: True

trainer:
    max_epochs: 10
    gpus: 1

callbacks:
    ModelCheckpoint:
        dirpath: 'run/checkpoints'
        filename: '{epoch}-{val_loss:.2f}'
        save_top_k: -1
        monitor: 'valid/loss'

    ImageLogger:
        RGB_image:
            image1: [0,1,2]
            image2: [2,1,0]
        RGB_target:
            image1: [0,0,0]
        RGB_output:
            image1: [0,0,0]
        normalize: True
        log_probabilities: False
        num_images:
        on_validation_epoch_end: True
        on_train_epoch_end: True

    LearningRateMonitor:


loggers:
    TensorBoardLogger:
        save_dir: 'run/lightning_logs'
    WandbLogger:
        save_dir: 'run/wandb'
        project: 'test'

optimizer:
    Adam:
        lr: 0.00001

lr_scheduler:
    ReduceLROnPlateau:

metrics:
    train:
        Accuracy:
            reduction: 'micro'
        Precision:
            reduction: 'micro'
        Recall:
            reduction: 'micro'

    valid:
        Accuracy:
            reduction: 'micro'
        Precision:
            reduction: 'micro'
        Recall:
            reduction: 'micro'

    test:
        Accuracy:
            reduction: 'micro'
        Precision:
            reduction: 'micro'
        Recall:
            reduction: 'micro'

loss:
    train:
        FocalLoss:
            weight: 1
            mode: *mode
            alpha: 0.25
            gamma: 2
            ignore_index: *ignore_index
    valid:
        DiceLoss:
            weight: 0.5
            mode: *mode
            ignore_index: *ignore_index
        FocalLoss:
            weight: 0.5
            mode: *mode
            ignore_index: *ignore_index

    test:
        DiceLoss:
            weight: 0.5
            mode: *mode
            ignore_index: *ignore_index
        FocalLoss:
            weight: 0.5
            mode: *mode
            ignore_index: *ignore_index

transfer_learning:
    # transfer_from_checkpoint:
    # trainer:
    #     max_epochs: 1
    #     gpus: 1

resume_from_ckpt:
